In [1]:
import numpy as np

In [29]:
W, H = (5,5)
center = (3, 3)
cw, ch = center 

In [36]:
y, x = np.ogrid[-ch+1:ch, -cw+1:cw]

In [42]:
print(y)
print(x)

[[-2]
 [-1]
 [ 0]
 [ 1]
 [ 2]]
[[-2 -1  0  1  2]]


In [40]:
cirFilter = np.zeros((H,W))
print(cirFilter)
r = 2.0

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [43]:
cirFilter[x*x+y*y<=r*r] = 1


print(cirFilter)

[[0. 0. 1. 0. 0.]
 [0. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 0.]
 [0. 0. 1. 0. 0.]]


In [61]:
import pandas as pd 
df = pd.DataFrame({"A":[1,4,7], "B":[2,5,8], "C":[3,6,9]})
df


A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [76]:
df2 = df.drop(['A','B'], axis=1)
df2

C
0  3
1  6
2  9

In [77]:
df

A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [67]:
df.iloc[0,2]

3

In [82]:
df.loc[:, 'A']

0    1
1    4
2    7
Name: A, dtype: int64

In [52]:
df[['A', 'B']]

A  B
0  1  2
1  4  5
2  7  8

In [57]:
from sklearn.datasets import load_iris # scikit-learn의 샘플 데이터 로드를 위해 import

iris = load_iris() # sample data load

In [58]:
import pandas as pd # 데이터 프레임으로 변환을 위해 임포트
import numpy as np # 고수학 연산을 위해 임포트

# feature_names 와 target을 레코드로 갖는 데이터프레임 생성
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)

In [59]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [68]:
df

A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [96]:
v = [76, 92, 135, 151, 188, 204, 245, 260, 296, 319, 356, 370, 407, 424, 463, 480, 520, 536, 576, 591, 630, 646, 687, 703, 742, 759, 797, 813, 853, 871, 908, 927, 963, 979, 1020, 1035, 1071, 1088, 1127, 1144, 776, 109]
v

[76,
 92,
 135,
 151,
 188,
 204,
 245,
 260,
 296,
 319,
 356,
 370,
 407,
 424,
 463,
 480,
 520,
 536,
 576,
 591,
 630,
 646,
 687,
 703,
 742,
 759,
 797,
 813,
 853,
 871,
 908,
 927,
 963,
 979,
 1020,
 1035,
 1071,
 1088,
 1127,
 1144,
 776,
 109]

In [97]:
type(v)

list

In [98]:
v_sorted = sorted(v)
print(v_sorted)

[76, 92, 109, 135, 151, 188, 204, 245, 260, 296, 319, 356, 370, 407, 424, 463, 480, 520, 536, 576, 591, 630, 646, 687, 703, 742, 759, 776, 797, 813, 853, 871, 908, 927, 963, 979, 1020, 1035, 1071, 1088, 1127, 1144]
